### ISSUE TITLE
Caused by: org.xml.sax.SAXParseException; systemId: http://www.osgi.org/xmlns/blueprint/v1.0.0/blueprint.xsd; lineNumber: 2; columnNumber: 35; s4s-elt-character: Non-whitespace characters are not allowed in schema elements other than 'xs:appinfo' and 'xs:documentation'. Saw '301 Moved Permanently'.

### ISSUE THREAD

**Issue by JavaNeed** [sachin-handiekar/spring-social-live#10]
I'm following your tutorial from the link : https://gist.github.com/sachin-handiekar/89b304598d23b034db73. When I use mentioned code I started facing the exact issue mentioned here : http://stackoverflow.com/questions/39667435/http-www-osgi-org-xmlns-blueprint-v1-0-0-blueprint-xsd-linenumber-2-columnn. 

Please guide

**Comment by sachin-handiekar** [comment]
Closing as not relevant to the spring-social-live project.
