### ISSUE TITLE
Maven could'nt find spring-social-live

### ISSUE THREAD

**Issue by ystreibel** [sachin-handiekar/spring-social-live#4]
Hi,

Is it a deprecated project ?

I'm trying to add spring-social-live to my spring-social project and maven couldn't find the .jar.

This is my pom.xml declaration :

```
<spring-social-live.version>1.0.0-SNAPSHOT</spring-social-live.version>
...
<dependency>
      <groupId>org.springframework.social</groupId>
      <artifactId>spring-social-live</artifactId>
      <version>${spring-social-live.version}</version>
</dependency>
``` 

I saw on your quickstart project that the declaration on the pom.xml is comment.

**Comment by ShyykoSerhiy** [comment]
It's not on maven central. You'll need to build it by yourself.
```
git clone https://github.com/sachin-handiekar/spring-social-live.git
cd spring-social-live/spring-social-live/
mvn install
```
now you can use it in your project.

**Comment by ystreibel** [comment]
Hi @ShyykoSerhiy ,

Thanks for your answer.
I had already done that, but I thought that was available on the maven repository.
