### ISSUE TITLE
Add license information to pom.xml

### ISSUE THREAD

**Issue by elygre** [sachin-handiekar/spring-social-live#7]
Would it be possible to add license-information to POM.XML? This would simplify license audits and reporting, and should be fairly easy. The maven docs have all you need, at https://maven.apache.org/pom.html#Licenses.

Seeing that you use the Apache license, I believe you would only need the following:

    <licenses>
      <license>
        <name>Apache License, Version 2.0</name>
        <url>http://www.apache.org/licenses/LICENSE-2.0.txt</url>
      </license>
    </licenses>

A real life example can be found in https://github.com/Activiti/Activiti/blob/master/pom.xml#L1046.

**Comment by sachin-handiekar** [comment]
Added license info in pom.xml
